{"status":"OK","result":{"originalLocale":"en","allowViewHistory":true,"creationTimeSeconds":1505006869,"rating":-3,"authorHandle":"NutelIa","modificationTimeSeconds":1505007064,"id":54438,"title":"\u003cp\u003e(Gym) Runtime Error \u003ca href\u003d\"//codeforces.com/gym/100026\"\u003ehttp://codeforces.com/gym/100026\u003c/a\u003e Problem C\u003c/p\u003e","locale":"en","content":"\u003cdiv class\u003d\"ttypography\"\u003e\u003cp\u003eI sent a code for problem C in this contest: \u003ca href\u003d\"//codeforces.com/gym/100026\"\u003ehttp://codeforces.com/gym/100026\u003c/a\u003e and I got runtime error (I didn\u0027t have runtime error in my computer nor in custom invocation). I couldn\u0027t find out where the error came from so I simplified my code (knowing it would get WA) to find the source. One of the last codes I sent was: \u003c/p\u003e \u003cpre\u003e\u003ccode\u003e#include \u0026lt;bits/stdc++.h\u0026gt;\n\nusing namespace std;\nstruct punt{\n\tint x,y;\n};\ntypedef vector \u0026lt; punt \u0026gt; VE;\nint n,k;\nVE mines, pals;\nint main(){\n\tcin \u0026gt;\u0026gt; n \u0026gt;\u0026gt; k;\n\tpals \u003d VE(n);\n\tmines \u003d VE(k);\n\tfor(int i \u003d 0; i \u0026lt; n; i++) {\n\t\tint x,y;\n\t\tcin \u0026gt;\u0026gt; x \u0026gt;\u0026gt; y;\n\t\tpals[i] \u003d {x,y};\n\t}\n\tfor(int i \u003d 0; i \u0026lt; k; i++) {\n\t\tint x,y;\n\t\tcin \u0026gt;\u0026gt; x \u0026gt;\u0026gt; y;\n\t\tmines[i] \u003d {x,y};\n\t}\n\tcout \u0026lt;\u0026lt; \u0026quot;** \u0026quot; \u0026lt;\u0026lt; mines[0].x \u0026lt;\u0026lt; \u0027 \u0027 \u0026lt;\u0026lt; mines[0].y \u0026lt;\u0026lt; endl;\n}\n\u003c/code\u003e\u003c/pre\u003e\u003cp\u003eAnd I still got runtime error. Checking the test case with a friend who has \u0026quot;coach mode\u0026quot; enabled I could find out k !\u003d 0 (as it corresponds to first test case in the sample). The source of the runtime error is the access to mines[0] but I don\u0027t understand why. Moreover, when I change the last few lines to these ones: \u003c/p\u003e \u003cpre\u003e\u003ccode\u003efor(int i \u003d 0; i \u0026lt; k; i++) {\n\tint x,y;\n\tcin \u0026gt;\u0026gt; x \u0026gt;\u0026gt; y;\n\tmines[i] \u003d {x,y};\n\tcout \u0026lt;\u0026lt; \u0026quot;** \u0026quot; \u0026lt;\u0026lt; mines[i].x \u0026lt;\u0026lt; \u0027 \u0027 \u0026lt;\u0026lt; mines[i].y \u0026lt;\u0026lt; endl;\n}\n\u003c/code\u003e\u003c/pre\u003e\u003cp\u003eI don\u0027t get runtime error. Instead this message is shown \u003c/p\u003e\u003cp\u003e\u003cimg alt\u003d\"alt text\" src\u003d\"/predownloaded/db/8d/db8d5281b5e1a1583cf39c7bdc28a51d6da0f1e2.png\" style\u003d\"max-width: 100.0%;max-height: 100.0%;\" /\u003e\u003c/p\u003e\u003cp\u003eCan someone help me? Is it a CF problem or mine?\u003c/p\u003e\u003c/div\u003e","tags":["mysterious runtime error","runtime error"]}}