{"status":"OK","result":{"originalLocale":"en","allowViewHistory":false,"creationTimeSeconds":1408752782,"rating":0,"authorHandle":"helioRocha","modificationTimeSeconds":1408752782,"id":13497,"title":"\u003cp\u003eRuntime error on test 1 (problem 118A, coded in python 2.7)\u003c/p\u003e","locale":"en","content":"\u003cdiv class\u003d\"ttypography\"\u003e\u003cp\u003eGreetings. I need some help, please. Code runs ok inside the custom test as well as offline in my pc. However, here is the \u003ccode\u003eJudgement Protocol\u003c/code\u003e:\u003c/p\u003e\u003cp\u003e\u003ccode\u003eTest: #1, time: 92 ms., memory: 20 KB, exit code: 1, checker exit code: 0, verdict: RUNTIME_ERROR\u003c/code\u003e\u003c/p\u003e\u003cp\u003eThe proposal was coded in python 2.7 as follows:\u003c/p\u003e \u003cpre\u003e\u003ccode\u003ez \u003d input().lower()\na \u003d range(len(z))\nb \u003d [z[i] for i in a]\nc \u003d range(len(b))\nd \u003d \u0027aeiouy\u0027\ne \u003d [b[j].replace(b[j],\u0026quot;.\u0026quot;+b[j]) for j in c if b[j] not in d]\nprint \u0027\u0027.join(e)\n\u003c/code\u003e\u003c/pre\u003e\u003cp\u003eThanks!\u003c/p\u003e\u003cp\u003e\u003ca href\u003d\"/contest/118/submission/7555759\" title\u003d\"Посылка 7555759 от helioRocha\"\u003e7555759\u003c/a\u003e \u003ca href\u003d\"/contest/118/problem/A\" title\u003d\"Codeforces Beta Round 89 (Div. 2)\"\u003e118A - Упражнение на строки\u003c/a\u003e\u003c/p\u003e\u003c/div\u003e","tags":["runtime error","118a","python 2"]}}