{"status":"OK","result":{"originalLocale":"en","allowViewHistory":true,"creationTimeSeconds":1513714244,"rating":-8,"authorHandle":"SerChirag","modificationTimeSeconds":1513714244,"id":56483,"title":"\u003cp\u003eAbrupt Runtime Error on PyPy\u003c/p\u003e","locale":"en","content":"\u003cdiv class\u003d\"ttypography\"\u003e\u003cp\u003eHi There !!\u003c/p\u003e\u003cp\u003eAttempted to solve this question: \u003ca href\u003d\"//codeforces.com/contest/902/submission/33428524\"\u003ehttp://codeforces.com/contest/902/submission/33428524\u003c/a\u003e Here is my solution: \u003ca href\u003d\"//codeforces.com/contest/902/submission/33428524\"\u003ehttp://codeforces.com/contest/902/submission/33428524\u003c/a\u003e\u003c/p\u003e\u003cp\u003eGot an abrupt runtime error !!! That too on the 25th test case. \u003c/p\u003e\u003cp\u003ePLEASE HELP !!!\u003c/p\u003e\u003c/div\u003e","tags":["#python","#pypy","#graph"]}}