{"status":"OK","result":{"originalLocale":"en","allowViewHistory":true,"creationTimeSeconds":1520315219,"rating":3,"authorHandle":"DaiDaiBear","modificationTimeSeconds":1520315219,"id":58197,"title":"\u003cp\u003eMetaphysics? Strange thing in Mo\u0027s algorithm\u003c/p\u003e","locale":"en","content":"\u003cdiv class\u003d\"ttypography\"\u003e\u003cp\u003e\u003cstrong\u003eThere is a quite strange thing when I try to solve \u003ca href\u003d\"/contest/940/problem/F\" title\u003d\"Codeforces Round 466 (Div. 2)\"\u003e940F - Машинное обучение\u003c/a\u003e, which is I submit a dozens of solutions and all of them get Runtime Error on test 46. But finally I create a new array and do not use it anywhere except give it some value in the beginning, and the solution got Accepted.\u003c/strong\u003e \u003c/p\u003e\u003cp\u003e\u003cstrong\u003eDetails can be found by the difference between \u003ca href\u003d\"/contest/940/submission/35980539\" title\u003d\"Посылка 35980539 от DaiDaiBear\"\u003e35980539\u003c/a\u003e and \u003ca href\u003d\"/contest/940/submission/35980530\" title\u003d\"Посылка 35980530 от DaiDaiBear\"\u003e35980530\u003c/a\u003e. The name of the unused array is \u003cem\u003edk\u003c/em\u003e, and initialized in the 4th line in solve() function, and not anywhere else appears.\u003c/strong\u003e \u003c/p\u003e\u003cp\u003e\u003cstrong\u003eDoes anyone know the reason why this happens? It really confused me and spend a lot of time on finding the error. Any comments will be helpful, thanks in advance!\u003c/strong\u003e\u003c/p\u003e\u003c/div\u003e","tags":["mos algorithm","metaphysics"]}}