{"status":"OK","result":{"originalLocale":"ru","allowViewHistory":true,"creationTimeSeconds":1480359667,"rating":10,"authorHandle":"T-D-K","modificationTimeSeconds":1480359667,"id":48683,"title":"\u003cp\u003eРешение падает на первом же тесте.\u003c/p\u003e","locale":"ru","content":"\u003cdiv class\u003d\"ttypography\"\u003e\u003cp\u003eГоспода, помогите разобраться что происходит. Вот две посылки: \u003ca href\u003d\"/contest/580/submission/22583523\" title\u003d\"Submission 22583523 by T-D-K\"\u003e22583523\u003c/a\u003e и \u003ca href\u003d\"/contest/580/submission/22583517\" title\u003d\"Submission 22583517 by T-D-K\"\u003e22583517\u003c/a\u003e. Первая падает с ошибкой исполнения на первом же тесте. Вторая успешно проходит все тесты. Оба решения отличаются только строчкой:\u003c/p\u003e\u003cp\u003eif (pos \u0026gt; n)  throw new Exception(\u0026quot;qqq\u0026quot;);\u003c/p\u003e\u003cp\u003eПричём проходит именно то решение, в котором эта строка есть.\u003c/p\u003e\u003c/div\u003e","tags":[]}}